[package]
name = "emu_rust"
version = "0.1.0"
authors = ["fotcorn <fotcorn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
num-traits = "0.2"
num-derive = "0.3"
